version: '3'

services:
  backend:
    build:
      context: ./backend
    ports:
      - "8000:8000"

  frontend:
    build:
      context: ./frontend
    ports:
      - "3500:3000"  # ホストの3500番ポートをコンテナの3000番ポートにマッピング
