#TripMate >> docker-compose
version: '3'

services:
  backend:
    build:
      context: ./backend
    container_name: backend
    ports:
      - "8000:8000"

  frontend:
    build:
      context: ./frontend
    container_name: frontend
    ports:
      - "3100:3000"  # ホストの3100番ポートをコンテナの3001番ポートにマッピング
