version: '3'

services:
  backend:
    build:
      context: ./backend
    ports:
      - "8300:8000"

  frontend:
    build:
      context: ./frontend
    ports:
      - "3300:3000"  # ホストの3300番ポートをコンテナの3000番ポートにマッピング
